#!/usr/local/bin/python35
import os
import os.path as osp

OUR_RT_DIR = os.getcwd() 
BASE_DIR = os.environ.get('UTP_BASE_DIR', '/dfcxact')
WORKING_DIR = os.environ.get('UTP_WORKING_DIR', osp.join(BASE_DIR, 'working'))
MTM_DIR = os.environ.get('UTP_MTM_DIR', osp.join(BASE_DIR, 'mtm'))
MACINUSE_DIR = os.environ.get('UTP_MACINUSE_DIR', osp.join(BASE_DIR, 'macinuse'))
WHERE_DIR = os.environ.get('UTP_MACINUSE_WHERE_DIR', osp.join(MACINUSE_DIR, 'where'))
MTSN_DIR = os.environ.get('UTP_MTSN_DIR', osp.join(BASE_DIR, 'mtsn'))
REPOS_DIR = osp.join(BASE_DIR, 'repos')
UTP_DIR = osp.join(BASE_DIR, 'utp')
OLD_MTSN_DIR = os.environ.get('UTP_OLD_MTSN_DIR', osp.join(BASE_DIR, 'old-mtsn'))
PRODUCT_DIR = os.environ.get('UTP_PRODUCT_DIR', osp.join(BASE_DIR, 'product'))
SITE_DIR = os.environ.get('UTP_SITE_DIR', osp.join(BASE_DIR, 'site'))
SITE_L2_FILE = osp.join(SITE_DIR, 'L2srvr.txt')
SITE_REMOTEMB_FILE = osp.join(SITE_DIR, 'remotemb.ini')
SITE_L1_IP_FILE = osp.join(SITE_DIR, 'l2_network_l1_ip')
UTP_LOCAL_DIR = osp.join(BASE_DIR, 'utp_local')
UTP_IP_FILE = osp.join(UTP_LOCAL_DIR, 'self_ip')
UTP_L2_IP_FILE = osp.join(UTP_LOCAL_DIR, 'l2_ip')
UTP_GEO_IP_FILE = osp.join(UTP_LOCAL_DIR, 'geo_ip')
UTP_SITE_FILE = osp.join(UTP_LOCAL_DIR, 'site')
UTP_SERVER_DETAIL = osp.join(UTP_LOCAL_DIR, 'server_detail')
LCR_BASE_DIR = os.environ.get('UTP_LCR_BASE_DIR', osp.join(BASE_DIR, 'lcr'))
PILOT_CRITERIA_DIR = osp.join(LCR_BASE_DIR, 'pilot')
STAT_DIR = osp.join(LCR_BASE_DIR, 'stat')
PILOT_STAT_DIR = osp.join(STAT_DIR, 'pilot')
REPO_CACHE = osp.join(LCR_BASE_DIR, 'cache')
DATA_ROOT = osp.join(BASE_DIR, 'data')
RETHINK_DATA_ROOT = osp.join(DATA_ROOT, 'rethinkdb')
GUI_DATA_ROOT = osp.join(DATA_ROOT, 'gui')
UUT_MAP_FILE = osp.join(UTP_LOCAL_DIR, 'uut_map')
SERVER_CRT_FILE = osp.join(UTP_LOCAL_DIR, 'server.crt')
TRUSTED_CA_CERT = osp.join(UTP_LOCAL_DIR, 'tls/trusted_ca.pem')
CLIENT_CERT = osp.join(UTP_LOCAL_DIR, 'tls/client/client_certificate.pem')
CLIENT_KEY = osp.join(UTP_LOCAL_DIR, 'tls/client/client_key.pem') 
TEST_CERT = osp.join(UTP_LOCAL_DIR, 'tls/test/test_certificate.pem')
TEST_KEY = osp.join(UTP_LOCAL_DIR, 'tls/test/test_key.pem')
SEQ_LINE = 'SEQ_LINE'
SEQ_GUID_MAP = 'SEQ_GUID_MAP'
SEQ_TEST_CASE = 'SEQ_TEST_CASE'
SEQ_CURRENT_OP = 'SEQ_CURRENT_OP'
SEQ_OP_PASSCOUNT = 'SEQ_OP_PASSCOUNT'
SEQ_IN_FAIL_BLOCK = 'SEQ_IN_FAIL_BLOCK'
RUNSEQS_PID = 'RUNSEQS_PID'
CURRENT_SEQ = 'CURRENT_SEQ'
UTP_DATA_VIRTUAL_HOST = '/utpdata'
UTP_EX_EVENT = 'utp-ex-event'
UTP_EX_REALTIME = 'utp-ex-realtime'
UTP_Q_EVENT_UUT = 'utp-q-event-uut'
UTP_Q_EVENT_PLATFORM = 'utp-q-event-platform'
UUT_ROUTE_KEY = 'uut'
PLATFORM_ROUTE_KEY = 'platform'
UUT_STATE_ROUTE = 'uut.state'
SEQ_GUID = 'SEQ_GUID'
OP_GUID = 'OP_GUID'
UTP_PRODUCTION = 'UTP_PRODUCTION'
FAIL_STATE = 'FAIL'
RUN_STATE = 'RUN'
UWIP_STATE = 'UWIP'
PASS_STATE = 'PASS'
START_STATE = 'START'
END_STATE = 'END'
REPAIR_STATE = 'REPAIR'
MTSN_SUBLOCATION = 'MTSN_SUBLOCATION'
UTP_SN = 'UTP_SN'
ERROR_LOG_GLOB = 'error[._]*'
TEST_LOG_GLOB = 'test.log'
UTP_MONUMBER = 'UTP_MONUMBER'
